export const plans = [
    {
        "zctppT_ID": 123,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 13,
        "zctppT_Description": "Connecting rod short",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 12,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-30T11:58:58",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 15,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "543527",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 89,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 122,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 21,
        "zctppT_Description": "Test-Part",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 10,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-29T17:39:58",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "Test-19072024",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 599,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 121,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 21,
        "zctppT_Description": "Test-Part",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 5,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-26T17:32:49",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "Test-19072024",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 135,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 120,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 345,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-26T11:19:28",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 76,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 118,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": false,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 34,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-23T15:54:04",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 14,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 47,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 117,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 13,
        "zctppT_Description": "Connecting rod short",
        "zctppT_Status": false,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 112,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-23T15:20:39",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "543527",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 12,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 116,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": false,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 112,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-23T15:13:02",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 36,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 115,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": false,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 71,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-23T15:04:09",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 0,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 114,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 13,
        "zctppT_Description": "Connecting rod short",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 8,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-23T11:38:44",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "543527",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 38,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 113,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 13,
        "zctppT_Description": "Connecting rod short",
        "zctppT_Status": false,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 6,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-22T17:24:12",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 15,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "543527",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 37,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 112,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 123,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-22T15:26:14",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 34,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 111,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": false,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 4040,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-21T11:26:28",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 2,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 110,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 13,
        "zctppT_Description": "Connecting rod short",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 2,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-20T13:03:32",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 15,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "543527",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 35,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 109,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 23,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-19T11:52:04",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 14,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 37,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 108,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 18,
        "zctppT_Description": "Updated Test Part",
        "zctppT_Status": true,
        "zctppT_Template_Type": 2,
        "zctppT_Revision_Number": 1,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-19T11:20:35",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 14,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "Test_15072024",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Receiving",
        "zctppT_ZCTPTP_Parameters_Count": 34,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 107,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 12,
        "zctppT_Description": "Manish_Testing",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 111,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-19T11:07:41",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 14,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "123",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 34,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    },
    {
        "zctppT_ID": 106,
        "zctppT_Partner_ID": 37,
        "zctppT_Part_ID": 21,
        "zctppT_Description": "Test-Part",
        "zctppT_Status": true,
        "zctppT_Template_Type": 1,
        "zctppT_Revision_Number": 1,
        "zctppT_Created_By": 40,
        "zctppT_Created_On": "2024-07-19T11:05:19",
        "zctppT_SPC_Sample_Size": 5,
        "zctppT_Default_Tolerance_ID": 0,
        "zctppT_MM_TO_INCH_CONVERSION": true,
        "zctptD_Part_Template_ID": 0,
        "zctptD_Drawing_Path": null,
        "zctptD_SR_No": 0,
        "gcmP_Part_Number": "Test-19072024",
        "gcmP_Variant_Name": null,
        "gcmU_Username": "nikhilsarode",
        "gcmU_Name": "Nikhil Sarode",
        "gcmO_Name": null,
        "zccS_Name": null,
        "zctptD_Page_No": null,
        "zctptD_Drawing_Id": null,
        "zctppT_Template_Code": "Manufacturing",
        "zctppT_ZCTPTP_Parameters_Count": 196,
        "zctppT_Part_Parameters": null,
        "zctppT_Part_Drawings": null
    }
]
